include:
  - project: "jean.laneurit/ros_gitlab_ci"
    file: ".gitlab-ci.yml"


variables:
  PKGS_TO_BUILD_TEST: "husky_bringup husky_description husky_hardware"
  ROSDEP_SKIP_KEYS: "can_hardware wiferion_charger valence_bms_driver ewellix_driver"
