<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="chassis">

    <xacro:macro name="chassis_visual">
        <visual>
            <origin
                xyz="${aabb_center_x-body_reference_x} ${aabb_center_y}  ${aabb_center_z-chassis_height-0.130}"
                rpy="0 0 0" />
            <geometry>
                <mesh
                    filename="file://$(find clearpath_platform_description)/meshes/a200/base_link.stl" />
            </geometry>
        </visual>
    </xacro:macro>


</robot>